# Generated by Django 4.2.3 on 2023-07-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchmate', '0003_watchlist_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='platform',
        ),
    ]
